"use strict";var _reactDom=require("react-dom"),React=require("react"),assign=require("object-assign"),normalize=require("react-style-normalizer"),EVENT_NAMES=require("react-event-names"),getMenuOffset=require("../getMenuOffset"),prepareChildren=require("./prepareChildren"),Menu=require("../Menu"),MenuItemCell=require("../MenuItemCell"),emptyFn=function(){},createClass=require("create-react-class");function toUpperFirst(g){return g?g.charAt(0).toUpperCase()+g.substring(1):""}var MenuItem=createClass({displayName:"ReactMenuItem",getInitialState:function(){return{}},getDefaultProps:function(){return{isMenuItem:!0,interactionStyles:!0,style:{cursor:"pointer",userSelect:"none",boxSizing:"border-box"},expander:"\u203A"}},render:function(){var h=this.prepareProps(this.props,this.state);return React.createElement("tr",h)},componentDidMount:function(){this.didMount=!0},prepareProps:function(h,i){var j={};return assign(j,h),j.theme=this.prepareTheme(j),j.mouseOver=!!i.mouseOver,j.active=!!i.active,j.disabled=!!j.disabled,j.style=this.prepareStyle(j),j.className=this.prepareClassName(j),j.children=this.prepareChildren(j),j.onClick=this.handleClick.bind(this,j),j.onMouseEnter=this.handleMouseEnter.bind(this,j),j.onMouseLeave=this.handleMouseLeave.bind(this,j),j.onMouseDown=this.handleMouseDown,j.onMouseMove=this.handleMouseMove,j},prepareTheme:function(h){var i=h.themes=h.themes||this.constructor.theme||THEME,j=h.theme;return"string"==typeof j&&(j=i[j]),j||i.default},handleClick:function(h,i){return h.disabled?void i.stopPropagation():void(this.props.onClick||this.props.fn||emptyFn)(i,h,h.index)},handleMouseMove:function(){},handleMouseDown:function(){var h=function(){this.setState({active:!1}),window.removeEventListener("mouseup",h)}.bind(this);window.addEventListener("mouseup",h),this.setState({active:!0})},showMenu:function(h,i){i.showMenu(h,offset)},handleMouseEnter:function(h,i){if(!h.disabled){var j={x:i.pageX,y:i.pageY};if(this.setState({mouseOver:!0}),h.onMenuItemMouseOver){var k;h.menu&&(k=getMenuOffset((0,_reactDom.findDOMNode)(this))),h.onMenuItemMouseOver(h,k,j)}}},handleMouseLeave:function(h,i){if(!h.disabled){var j={x:i.pageX,y:i.pageY};this.didMount&&this.setState({active:!1,mouseOver:!1}),h.onMenuItemMouseOut&&h.onMenuItemMouseOut(h,j)}},prepareChildren:prepareChildren,prepareClassName:function(h){var i=h.className||"";return i+=" menu-row",h.disabled?i+=" disabled "+(h.disabledClassName||""):(h.mouseOver&&(i+=" over "+(h.overClassName||"")),h.active&&(i+=" active "+(h.activeClassName||"")),h.expanded&&(i+=" expanded "+(h.expandedClassName||""))),i},prepareDefaultStyle:function(h){var i=assign({},h.style);return h.disabled&&assign(i,h.defaultDisabledStyle),i},prepareComputedStyleNames:function(h){var i=["style"];if(h.disabled)return i.push("disabledStyle"),i;h.expanded&&i.push("expandedStyle");//names is something like ['style','expandedStyle']
//
//now we add over and active styles
var j;h.mouseOver&&(j=i.map(function(l){return"over"+toUpperFirst(l)}));var k;return h.active&&(k=i.map(function(l){return"active"+toUpperFirst(l)})),j&&i.push.apply(i,j),k&&i.push.apply(i,k),i},prepareStyle:function(h){var i=assign({},this.prepareDefaultStyle(h)),j=this.prepareComputedStyleNames(h),k=h.theme,l=h.themes;return k&&(h.applyDefaultTheme&&k!=l.default&&l.default&&j.forEach(function(m){assign(i,l.default[m])}),j.forEach(function(m){assign(i,k[m])})),(h.onThemeStyleReady||emptyFn)(i,h),j.forEach(function(m){assign(i,h[m])}),(h.onStyleReady||emptyFn)(i,h),normalize(i);// assign(style, props.defaultStyle, props.style)
// if (props.disabled){
//     assign(style, props.defaultDisabledStyle, props.disabledStyle)
// } else {
//     if (props.interactionStyles){
//         if (props.expanded){
//             assign(style, props.defaultExpandedStyle, props.expandedStyle)
//         }
//         if (props.mouseOver){
//             assign(style, props.defaultOverStyle, props.overStyle)
//         }
//         if (props.active){
//             assign(style, props.defaultActiveStyle, props.activeStyle)
//         }
//     }
// }
// return normalize(style)
}});module.exports=MenuItem;