"use strict";var _reactDom=require("react-dom");function emptyFn(){}var React=require("react"),assign=require("object-assign"),Region=require("region-align"),inTriangle=require("point-in-triangle"),hasTouch=require("has-touch"),normalize=require("react-style-normalizer"),getMenuOffset=require("./getMenuOffset"),getConstrainRegion=require("./align/getConstrainRegion"),getItemStyleProps=require("./getItemStyleProps"),renderSubMenu=require("./renderSubMenu"),renderChildren=require("./renderChildren"),prepareItem=require("./prepareItem"),propTypes=require("./propTypes"),ScrollContainer=require("./ScrollContainer"),MenuItem=require("./MenuItem"),MenuClass=React.createClass({displayName:"Menu",propTypes:propTypes,getDefaultProps:function(){return{isMenu:!0,constrainTo:!0,enableScroll:!0,interactionStyles:!0,applyDefaultTheme:!0,defaultStyle:{display:"inline-block",boxSizing:"border-box",position:"relative",background:"white",//theme props
border:"1px solid rgb(46, 153, 235)"},defaultSubMenuStyle:{position:"absolute"},subMenuStyle:null,scrollerProps:{},columns:["label"],items:null,visible:!0,defaultItemStyle:{},itemStyle:{},defaultItemOverStyle:{},itemOverStyle:{},defaultItemDisabledStyle:{},itemDisabledStyle:{},defaultItemExpandedStyle:{},itemExpandedStyle:{},defaultCellStyle:{},cellStyle:{},stopClickPropagation:!0}},getInitialState:function(){return{mouseOver:!1}},componentWillUnmount:function(){this.didMount=!1},componentDidMount:function(){(this.props.onMount||emptyFn)(this),this.didMount=!0,(this.props.constrainTo||this.props.alignTo)&&!this.props.subMenu&&setTimeout(function(){if(this.isMounted()){var p,q=this.props,r=Region.from((0,_reactDom.findDOMNode)(this.refs.scrollContainer)),s=(0,_reactDom.findDOMNode)(this),t=Region.from(s),u=t.height,v=r.height+u,w=Region({left:t.left,right:t.right,top:t.top,bottom:t.top+v}),x=q.constrainTo?getConstrainRegion(q.constrainTo):null;//get clientHeight of this dom node, so as to account for padding
//build the actual region of the menu
if(q.alignTo){var y=Region.from(s.parentNode),z=Region.from(q.alignTo);w.alignTo(z,q.alignPositions,{offset:q.alignOffset,constrain:x});var A=w.top-y.top,B=w.left-y.left;p={style:{left:B,top:A}}}x&&(p=p||{},w.bottom>x.bottom&&(p.maxHeight=x.bottom-w.top-u)),p&&this.setState(p)}}.bind(this),0)},prepareProps:function(p,q){var r={};return assign(r,this.props),r.style=this.prepareStyle(r,q),r.className=this.prepareClassName(r),r.itemStyleProps=getItemStyleProps(r,q),r.children=this.prepareChildren(r,q),r.scrollerProps=this.prepareScrollerProps(r),r},prepareScrollerProps:function(p){return assign({},p.scrollerProps)},prepareChildren:function(p,q){var r=p.children;return p.items&&p.items.length&&(r=p.items.map(this.prepareItem.bind(this,p,q))),r},prepareItem:prepareItem,prepareClassName:function(p){var q=p.className||"";return q+=" z-menu",q},prepareStyle:function(p,q){var r=p.subMenu?p.defaultSubMenuStyle:null,s=assign({},p.defaultStyle,r,p.style,p.subMenuStyle);if(p.visible&&(!p.items||p.items.length)||(s.display="none"),p.absolute&&(s.position="absolute"),p.at){var t=Array.isArray(p.at),u={left:t?p.at[0]:void 0===p.at.left?p.at.x||p.at.pageX:p.at.left,top:t?p.at[1]:void 0===p.at.top?p.at.y||p.at.pageY:p.at.top};assign(s,u)}return q.style&&assign(s,q.style),!this.didMount&&(p.constrainTo||p.alignTo)&&!p.subMenu&&(s.visibility="hidden",s.maxHeight=0,s.overflow="hidden"),normalize(s)},/////////////// RENDERING LOGIC
renderSubMenu:renderSubMenu,render:function(){var p=this.state,q=this.prepareProps(this.props,p),r=this.renderSubMenu(q,p),s=this.renderChildren(q,p);return React.createElement("div",q,r,React.createElement(ScrollContainer,{onMouseEnter:this.handleMouseEnter,onMouseLeave:this.handleMouseLeave,scrollerProps:q.scrollerProps,ref:"scrollContainer",enableScroll:q.enableScroll,maxHeight:p.maxHeight||q.maxHeight},React.createElement("table",{ref:"table",style:{borderSpacing:0}},React.createElement("tbody",null,s))))},renderChildren:renderChildren,////////////////////////// BEHAVIOUR LOGIC
handleMouseEnter:function(){this.setState({mouseInside:!0}),this.onActivate()},handleMouseLeave:function(){this.setState({mouseInside:!1}),this.state.menu||this.state.nextItem||this.onInactivate()},onActivate:function(){this.state.activated||(this.setState({activated:!0}),(this.props.onActivate||emptyFn)())},onInactivate:function(){this.state.activated&&(this.setState({activated:!1}),// console.log('inactivate')
(this.props.onInactivate||emptyFn)())},//we also need mouseOverSubMenu: Boolean
//since when from a submenu we move back to a parent menu, we may move
//to a different menu item than the one that triggered the submenu
//so we should display another submenu
handleSubMenuMouseEnter:function(){this.setState({mouseOverSubMenu:!0})},handleSubMenuMouseLeave:function(){this.setState({mouseOverSubMenu:!1})},isSubMenuActive:function(){return this.state.subMenuActive},onSubMenuActivate:function(){this.setState({subMenuActive:!0})},onSubMenuInactivate:function(){var p=+new Date,q=this.state.nextItem,r=this.state.nextTimestamp||0;this.setState({subMenuActive:!1,timestamp:p},function(){setTimeout(function(){return p!=this.state.timestamp||q&&100>p-r?void this.setItem(this.state.nextItem,this.state.nextOffset):void(!this.isSubMenuActive()&&this.setItem())}.bind(this),10)})},removeMouseMoveListener:function(){this.onWindowMouseMove&&(window.removeEventListener("mousemove",this.onWindowMouseMove),this.onWindowMouseMove=null)},onMenuItemMouseOut:function(p,q){this.state.menu&&this.setupCheck(q)},/**
     * Called when mouseout happens on the item for which there is a submenu displayed
     */onMenuItemMouseOver:function(p,q){if(this.didMount){var r=p.menu;+new Date,r&&(this.state.menu?this.setNextItem(p,q):this.setItem(p,q))}},setupCheck:function(p){// + tolerance
// - tolerance
if(this.didMount){var q=5,r=(0,_reactDom.findDOMNode)(this),s=r.querySelector(".z-menu");if(s){var t=Region.from(s),u=t.left,v=t.top,w=t.left,x=t.bottom;"left"==this.subMenuPosition&&(u=t.right,w=t.right);var y=p.x+("left"==this.subMenuPosition?q:-q),z=p.y,A=[[u,v],[w,x],[y,z]];this.removeMouseMoveListener(),this.onWindowMouseMove=function(B){var C=[B.pageX,B.pageY];inTriangle(C,A)||(this.removeMouseMoveListener(),!this.state.mouseOverSubMenu&&this.setItem(this.state.nextItem,this.state.nextOffset))}.bind(this),window.addEventListener("mousemove",this.onWindowMouseMove)}}},setNextItem:function(p,q){var r=+new Date;this.setState({timestamp:r,nextItem:p,nextOffset:q,nextTimestamp:+new Date})},setItem:function(p,q){var r=p?p.menu:null;// if (!menu){
//     return
// }
this.removeMouseMoveListener(),this.didMount&&(!r&&!this.state.mouseInside&&this.onInactivate(),this.setState({itemProps:p,menu:r,menuOffset:q,timestamp:+new Date,nextItem:null,nextOffset:null,nextTimestamp:null}))},onMenuItemExpanderClick:function(p){p.nativeEvent.expanderClick=!0},onMenuItemClick:function(p,q,r){var s=p.isPropagationStopped();if(this.props.stopClickPropagation&&p.stopPropagation(),hasTouch&&q&&p&&p.nativeEvent&&p.nativeEvent.expanderClick){var t={x:p.pageX,y:p.pageY},u=getMenuOffset(p.currentTarget);return void this.onMenuItemMouseOver(q,u,t)}s||(q&&(this.props.onClick||emptyFn)(p,q,r),this.onChildClick(p,q))},onChildClick:function(p,q){(this.props.onChildClick||emptyFn)(p,q),this.props.parentMenu&&this.props.parentMenu.onChildClick(p,q)}});MenuClass.themes=require("./MenuItem/themes"),module.exports=MenuClass;